<?php

declare(strict_types=1);

namespace Storm\Saga\Schema;

/**
 * Raw PostgreSQL DDL for `workflow_timers`, the due-time scheduling table: one table for all timer
 * kinds and the single source of truth for state `timeout`s, back-off `kick`s, and the instance-wide
 * `global` deadline. Drained by `storm:saga:timers`.
 *
 * `kind` is `timeout`, `kick`, or `global`. The unique `(workflow_type, correlation_id, state_key, kind)`
 * makes arming idempotent, so re-arming the same timer is a no-op upsert. `claimed_at` marks a row
 * claimed by a runner via `FOR UPDATE SKIP LOCKED`. The `fire_at` index serves the runner's hot claim;
 * it is a FULL index, not partial on `claimed_at IS NULL`, so the claim's `fire_at <= now ORDER BY
 * fire_at` short-circuits at the first not-yet-due row even under the re-claim lease OR, whereas a
 * partial index would force a seq scan there. This durable table, with the runner re-claiming due rows
 * on restart, is Storm's "DurabilityAgent": a lost in-flight dispatch is re-sent from its row.
 *
 * `attempts` counts FAILED drives, recorded by the runner on a throw and reset by any re-arm.
 * `parked_at` quarantines a poison row out of the claim, whether a permanent failure whose workflow was
 * purged or an exhausted attempts budget, so one bad timer can never crash-loop the daemon while its
 * co-claimed siblings wait out the lease forever. `last_error` is the parking forensics.
 *
 * `fillfactor = 70` is structural, not tuning, hence schema-owned unlike the autovacuum scale-factor an
 * install ALTERs app-side. The claim's `SET claimed_at` touches no indexed column, since `claimed_at`,
 * `attempts`, `parked_at`, and `last_error` live outside all three indexes, so with in-page headroom
 * every claim is a HOT update with zero new entries across the pk, due, and unique indexes. At the
 * default 100 the pages sit full and nearly every claim goes non-HOT instead, ballooning the
 * four-text-column unique index under a flood of runners. A re-arm changes the indexed `fire_at`, so it
 * stays legitimately non-HOT.
 */
final class WorkflowTimersSchema
{
    /**
     * @return list<string>
     */
    public static function up(): array
    {
        return [
            /** @lang PostgreSQL */
            <<<'SQL'
                CREATE TABLE IF NOT EXISTS workflow_timers (
                    id             bigint GENERATED BY DEFAULT AS IDENTITY,
                    workflow_type  text   NOT NULL,
                    correlation_id text   NOT NULL,
                    state_key      text   NOT NULL,
                    kind           text   NOT NULL,
                    fire_at        timestamptz(6) NOT NULL,
                    claimed_at     timestamptz(6),
                    attempts       integer NOT NULL DEFAULT 0,
                    parked_at      timestamptz(6),
                    last_error     text,
                    created_at     timestamptz(6) NOT NULL DEFAULT clock_timestamp(),
                    CONSTRAINT workflow_timers_pk PRIMARY KEY (id),
                    CONSTRAINT workflow_timers_unique UNIQUE (workflow_type, correlation_id, state_key, kind),
                    CONSTRAINT workflow_timers_kind_chk CHECK (kind IN ('timeout', 'kick', 'global', 'schedule')),
                    CONSTRAINT workflow_timers_attempts_chk CHECK (attempts >= 0)
                ) WITH (fillfactor = 70)
                SQL,
            /** @lang PostgreSQL */
            <<<'SQL'
                CREATE INDEX IF NOT EXISTS workflow_timers_due_idx ON workflow_timers (fire_at)
                SQL,
        ];
    }

    /**
     * @return list<string>
     */
    public static function down(): array
    {
        return [
            /** @lang PostgreSQL */
            'DROP TABLE IF EXISTS workflow_timers',
        ];
    }
}
