<?php

declare(strict_types=1);

namespace Storm\Saga\Schema;

use Storm\Message\Message;
use Storm\Saga\Outbox\OutboxStatus;
use Storm\Serializer\MessageSerializer;

/**
 * Raw PostgreSQL DDL for `workflow_outbox`, a saga's outgoing commands. A step that issues a command
 * writes a row here in the step's transaction, atomic with the state advance. `SagaOutboxRelay`
 * dispatches it to its `bus` after commit, the same dual-write fix as the event outbox but on a
 * saga-owned table, so it carries no event-store `position` or `version`, only the command.
 *
 * `header` and `content` hold the serialized `Message`, which the relay rebuilds via the
 * `MessageSerializer`. `status` uses the {@see OutboxStatus} vocabulary, and the lifecycle and
 * per-status retention rule live THERE rather than here, that enum being the shared source this
 * schema binds its partial index from. The partial index on the pending rows is the relay's hot
 * query.
 *
 * `effect_group` names the concurrent arm a command belongs to, null for the ungrouped common case.
 * It is the targeted recall's key, so a race can cancel ONE losing arm's still-pending commands
 * without touching its siblings.
 *
 * Being separate from `es_outbox` is a design decision and not a temporary split: the event outbox
 * encodes per-aggregate ordering and event upcasting, this one encodes neither, and those different
 * invariants are what keep them two stacks.
 *
 * @see \Storm\Message\Message
 * @see \Storm\Serializer\MessageSerializer
 * @see WorkflowOutboxArchiveSchema the append-only audit sibling under `disposal: archive`
 */
final class WorkflowOutboxSchema
{
    /**
     * @return list<string>
     */
    public static function up(): array
    {
        return [
            /** @lang PostgreSQL */
            <<<'SQL'
                CREATE TABLE IF NOT EXISTS workflow_outbox (
                    id              bigint GENERATED BY DEFAULT AS IDENTITY,
                    workflow_type   text NOT NULL,
                    correlation_id  text NOT NULL,
                    bus             text NOT NULL,
                    header          jsonb NOT NULL,
                    content         jsonb NOT NULL,
                    status          text NOT NULL DEFAULT 'pending',
                    attempts        integer NOT NULL DEFAULT 0,
                    next_attempt_at timestamptz(6),
                    last_error      text,
                    issued_from_state text NOT NULL DEFAULT '',
                    issued_at_version integer NOT NULL DEFAULT -1,
                    effect_group    text,
                    generation      integer NOT NULL DEFAULT 1,
                    evidence        text NOT NULL DEFAULT 'unknown',
                    created_at      timestamptz(6) NOT NULL DEFAULT clock_timestamp(),
                    processed_at    timestamptz(6),
                    CONSTRAINT workflow_outbox_pk PRIMARY KEY (id),
                    CONSTRAINT workflow_outbox_status_chk CHECK (status IN ('pending', 'published', 'failed', 'cancelled')),
                    CONSTRAINT workflow_outbox_evidence_chk CHECK (evidence IN ('uncommitted', 'unknown')),
                    CONSTRAINT workflow_outbox_attempts_chk CHECK (attempts >= 0),
                    CONSTRAINT workflow_outbox_generation_chk CHECK (generation >= 1),
                    CONSTRAINT workflow_outbox_issued_at_version_chk CHECK (issued_at_version >= -1)
                )
                SQL,
            /** @lang PostgreSQL */
            sprintf(
                "CREATE INDEX IF NOT EXISTS workflow_outbox_pending_idx ON workflow_outbox (id) WHERE status = '%s'",
                OutboxStatus::Pending->value,
            ),
            // the targeted recall's hot path: cancel one effect group's still-pending rows without
            // touching its sibling arms; near-free, since only grouped commands ever enter it
            /** @lang PostgreSQL */
            sprintf(
                "CREATE INDEX IF NOT EXISTS workflow_outbox_group_pending_idx ON workflow_outbox (workflow_type, correlation_id, effect_group) WHERE status = '%s' AND effect_group IS NOT NULL",
                OutboxStatus::Pending->value,
            ),
            // the reconcile scan's side of the strandedByFailedEffect join; near-free, since only
            // dead-letters ever enter it
            /** @lang PostgreSQL */
            sprintf(
                "CREATE INDEX IF NOT EXISTS workflow_outbox_failed_corr_idx ON workflow_outbox (correlation_id) WHERE status = '%s'",
                OutboxStatus::Failed->value,
            ),
            // the dead-letter FLIP's path, markFailed(): it runs once per terminal
            // WorkerMessageFailedEvent, so it is busiest exactly during a mass dead-letter, over a
            // table sized by the retention window; without this the flip is a sequential scan per
            // failed command at the worst possible moment
            /** @lang PostgreSQL */
            sprintf(
                "CREATE INDEX IF NOT EXISTS workflow_outbox_published_corr_idx ON workflow_outbox (correlation_id) WHERE status = '%s'",
                OutboxStatus::Published->value,
            ),
        ];
    }

    /**
     * @return list<string>
     */
    public static function down(): array
    {
        return [
            /** @lang PostgreSQL */
            'DROP TABLE IF EXISTS workflow_outbox',
        ];
    }
}
